### ISSUE TITLE
not rendering properly data and aria attributes

### ISSUE THREAD

**Issue by totano** [Swizz/snabbdom-pragma#7]
data-* and aria-*
get rendered as [object Object] on OS X
snabbdom-pragma 1.8.0
they should be passed to h() function as attrs: { "data-id": "value" }, instead they are passed as attrs: { "data": { "id": "value"}}

**Comment by Swizz** [comment]
Right, this is due to the [modules-attribute](https://github.com/Swizz/snabbdom-pragma/tree/feature/write-some-docs#modules-attribute), which take the `data-*` as an object key river.

I will work on a fix ASAP.
I have an idea, I am going to declare Snabbdom modules for data and aria to keep Snabbdom-pragma core as smaller as possible. (and do the same for SVG too).

**Comment by Swizz** [comment]
Note : Desired behavior
```jsx
/* written */
const vnode = <div data-color="red" aria-hidden={true}/>

/* Once Transpiled */
const vnode = Snabbdom.createElement('div', { 'data-color': 'red', 'aria-hidden': true })

/* Once Executed */
const vnode = h('div', { attrs: { 'data-color': 'red', 'aria-hidden': true } }, [])
```

**Comment by Swizz** [comment]
[1.10.0](https://github.com/Swizz/snabbdom-pragma/releases/tag/1.10.0) which fix this is now out ! And [npm published](https://www.npmjs.com/package/snabbdom-pragma)
